### ISSUE TITLE
Error when updating to aws-kcl 2.0.0 unrecognized classpath option "-cp"

### ISSUE THREAD

**Issue by pratikjain5** [awslabs/amazon-kinesis-client-nodejs#68] opened 2019-03-15 20:27 UTC
==========================================================
Starting MultiLangDaemon ...
Unrecognized option: -cp "/var/app/current/node_modules/aws-kcl/lib/jars/amazon-kinesis-client-2.1.2.jar:/var/app/current/node_modules/aws-kcl/lib/jars/amazon-kinesis-client-multilang-2.1.2.jar:/var/app/current/node_modules/aws-kcl/lib/jars/animal-sniffer-annotations-1.14.jar:/var/app/current/node_modules/aws-kcl/lib/jars/annotations-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/apache-client-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/auth-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/aws-cbor-protocol-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/aws-core-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/aws-java-sdk-core-1.11.477.jar:/var/app/current/node_modules/aws-kcl/lib/jars/aws-json-protocol-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/aws-query-protocol-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/checker-qual-2.5.2.jar:/var/app/current/node_modules/aws-kcl/lib/jars/cloudwatch-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/commons-beanutils-1.9.3.jar:/var/app/current/node_modules/aws-kcl/lib/jars/commons-codec-1.10.jar:/var/app/current/node_modules/aws-kcl/lib/jars/commons-collections-3.2.2.jar:/var/app/current/node_modules/aws-kcl/lib/jars/commons-collections4-4.2.jar:/var/app/current/node_modules/aws-kcl/lib/jars/commons-io-2.6.jar:/var/app/current/node_modules/aws-kcl/lib/jars/commons-lang3-3.8.1.jar:/var/app/current/node_modules/aws-kcl/lib/jars/commons-logging-1.1.3.jar:/var/app/current/node_modules/aws-kcl/lib/jars/dynamodb-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/error_prone_annotations-2.1.3.jar:/var/app/current/node_modules/aws-kcl/lib/jars/flow-1.7.jar:/var/app/current/node_modules/aws-kcl/lib/jars/guava-26.0-jre.jar:/var/app/current/node_modules/aws-kcl/lib/jars/http-client-spi-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/httpclient-4.5.6.jar:/var/app/current/node_modules/aws-kcl/lib/jars/httpcore-4.4.10.jar:/var/app/current/node_modules/aws-kcl/lib/jars/ion-java-1.0.2.jar:/var/app/current/node_modules/aws-kcl/lib/jars/j2objc-annotations-1.1.jar:/var/app/current/node_modules/aws-kcl/lib/jars/jackson-annotations-2.9.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/jackson-core-2.9.8.jar:/var/app/current/node_modules/aws-kcl/lib/jars/jackson-databind-2.9.8.jar:/var/app/current/node_modules/aws-kcl/lib/jars/jackson-dataformat-cbor-2.9.8.jar:/var/app/current/node_modules/aws-kcl/lib/jars/jcommander-1.72.jar:/var/app/current/node_modules/aws-kcl/lib/jars/joda-time-2.8.1.jar:/var/app/current/node_modules/aws-kcl/lib/jars/jsr305-3.0.2.jar:/var/app/current/node_modules/aws-kcl/lib/jars/kinesis-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/logback-classic-1.2.3.jar:/var/app/current/node_modules/aws-kcl/lib/jars/logback-core-1.2.3.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-buffer-4.1.32.Final.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-codec-4.1.32.Final.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-codec-http-4.1.32.Final.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-codec-http2-4.1.32.Final.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-common-4.1.32.Final.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-handler-4.1.32.Final.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-nio-client-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-reactive-streams-2.0.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-reactive-streams-http-2.0.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-resolver-4.1.32.Final.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-transport-4.1.32.Final.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-transport-native-epoll-4.1.32.Final.jar:/var/app/current/node_modules/aws-kcl/lib/jars/netty-transport-native-unix-common-4.1.32.Final.jar:/var/app/current/node_modules/aws-kcl/lib/jars/profiles-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/protobuf-java-2.6.1.jar:/var/app/current/node_modules/aws-kcl/lib/jars/protocol-core-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/reactive-streams-1.0.2.jar:/var/app/current/node_modules/aws-kcl/lib/jars/regions-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/rxjava-2.1.14.jar:/var/app/current/node_modules/aws-kcl/lib/jars/sdk-core-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/slf4j-api-1.7.25.jar:/var/app/current/node_modules/aws-kcl/lib/jars/sts-2.4.0.jar:/var/app/current/node_modules/aws-kcl/lib/jars/utils-2.4.0.jar:/var/app/current:/var/app/current"
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by pratikjain5** [comment] 2019-03-15 20:30
I am running app using command "node_modules/aws-kcl/bin/kcl-bootstrap --java /usr/bin/java -e -p ./kinesis.properties". Previous version library 0.8.0 works fine

**Comment by thecodeboss** [comment] 2019-03-20 22:05
Having the same issue

**Comment by pratikjain5** [comment] 2019-03-20 22:14
@thecodeboss 
I figured out the solution is in pull request [which](https://github.com/awslabs/amazon-kinesis-client-nodejs/pull/67/commits/207e57a179f0fa1982424bf353fcf694f78f8a45) has not been merged yet. I hope it helps.

**Comment by lancedikson** [comment] 2019-04-05 09:13
I have the same issue. @pfifer, could you please take a look at the PR (#67)? 🙏

**Comment by lancedikson** [comment] 2019-04-05 09:13
The PR seems to heal the bug.

**Comment by eugeneware** [comment] 2019-04-14 10:01
PR solves the issue for me on linux too

**Comment by MichaelHindley** [comment] 2019-04-24 12:00
Also experiencing this issue

**Comment by malekismail** [comment] 2019-05-03 20:39
@pfifer : we are still experiencing this issue, would you please advise when we can upgrade to the new version, thanks

**Comment by andrewm42** [comment] 2019-05-28 15:19
I am experiencing this issue on macOS and openjdk docker image.

**Comment by andrewm42** [comment] 2019-05-28 17:04
My specific error message:

> AM:kclnodejs am$ kcl-bootstrap --java /usr/bin/java -e -p samples/basic_sample/consumer/sample.properties 
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/amazon-kinesis-client-multilang-2.1.2.jar downloaded. 61 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/amazon-kinesis-client-2.1.2.jar downloaded. 60 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/kinesis-2.4.0.jar downloaded. 59 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-cbor-protocol-2.4.0.jar downloaded. 58 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jackson-dataformat-cbor-2.9.8.jar downloaded. 57 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-json-protocol-2.4.0.jar downloaded. 56 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/dynamodb-2.4.0.jar downloaded. 55 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/cloudwatch-2.4.0.jar downloaded. 54 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-nio-client-2.4.0.jar downloaded. 53 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-codec-http-4.1.32.Final.jar downloaded. 52 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-codec-http2-4.1.32.Final.jar downloaded. 51 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-codec-4.1.32.Final.jar downloaded. 50 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-transport-4.1.32.Final.jar downloaded. 49 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-resolver-4.1.32.Final.jar downloaded. 48 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-common-4.1.32.Final.jar downloaded. 47 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-buffer-4.1.32.Final.jar downloaded. 46 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-handler-4.1.32.Final.jar downloaded. 45 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-transport-native-epoll-4.1.32.Final.jar downloaded. 44 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-transport-native-unix-common-4.1.32.Final.jar downloaded. 43 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-reactive-streams-http-2.0.0.jar downloaded. 42 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-reactive-streams-2.0.0.jar downloaded. 41 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/reactive-streams-1.0.2.jar downloaded. 40 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/guava-26.0-jre.jar downloaded. 39 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jsr305-3.0.2.jar downloaded. 38 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/checker-qual-2.5.2.jar downloaded. 37 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/error_prone_annotations-2.1.3.jar downloaded. 36 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/j2objc-annotations-1.1.jar downloaded. 35 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/animal-sniffer-annotations-1.14.jar downloaded. 34 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/protobuf-java-2.6.1.jar downloaded. 33 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-lang3-3.8.1.jar downloaded. 32 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/slf4j-api-1.7.25.jar downloaded. 31 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/rxjava-2.1.14.jar downloaded. 30 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/sts-2.4.0.jar downloaded. 29 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-query-protocol-2.4.0.jar downloaded. 28 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/protocol-core-2.4.0.jar downloaded. 27 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/profiles-2.4.0.jar downloaded. 26 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/sdk-core-2.4.0.jar downloaded. 25 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jackson-core-2.9.8.jar downloaded. 24 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jackson-databind-2.9.8.jar downloaded. 23 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/auth-2.4.0.jar downloaded. 22 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/flow-1.7.jar downloaded. 21 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/http-client-spi-2.4.0.jar downloaded. 20 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/regions-2.4.0.jar downloaded. 19 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jackson-annotations-2.9.0.jar downloaded. 18 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/annotations-2.4.0.jar downloaded. 17 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/utils-2.4.0.jar downloaded. 16 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-core-2.4.0.jar downloaded. 15 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/apache-client-2.4.0.jar downloaded. 14 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/httpclient-4.5.6.jar downloaded. 13 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-codec-1.10.jar downloaded. 12 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/httpcore-4.4.10.jar downloaded. 11 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-java-sdk-core-1.11.477.jar downloaded. 10 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-logging-1.1.3.jar downloaded. 9 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/ion-java-1.0.2.jar downloaded. 8 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/joda-time-2.8.1.jar downloaded. 7 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/logback-classic-1.2.3.jar downloaded. 6 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/logback-core-1.2.3.jar downloaded. 5 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jcommander-1.72.jar downloaded. 4 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-io-2.6.jar downloaded. 3 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-collections4-4.2.jar downloaded. 2 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-beanutils-1.9.3.jar downloaded. 1 files remain.
> /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-collections-3.2.2.jar downloaded. 0 files remain.
> ==========================================================
> /usr/bin/java -cp /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/amazon-kinesis-client-2.1.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/amazon-kinesis-client-multilang-2.1.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/animal-sniffer-annotations-1.14.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/annotations-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/apache-client-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/auth-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-cbor-protocol-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-core-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-java-sdk-core-1.11.477.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-json-protocol-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-query-protocol-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/checker-qual-2.5.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/cloudwatch-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-beanutils-1.9.3.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-codec-1.10.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-collections-3.2.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-collections4-4.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-io-2.6.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-lang3-3.8.1.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-logging-1.1.3.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/dynamodb-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/error_prone_annotations-2.1.3.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/flow-1.7.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/guava-26.0-jre.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/http-client-spi-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/httpclient-4.5.6.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/httpcore-4.4.10.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/ion-java-1.0.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/j2objc-annotations-1.1.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jackson-annotations-2.9.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jackson-core-2.9.8.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jackson-databind-2.9.8.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jackson-dataformat-cbor-2.9.8.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jcommander-1.72.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/joda-time-2.8.1.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jsr305-3.0.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/kinesis-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/logback-classic-1.2.3.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/logback-core-1.2.3.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-buffer-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-codec-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-codec-http-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-codec-http2-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-common-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-handler-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-nio-client-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-reactive-streams-2.0.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-reactive-streams-http-2.0.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-resolver-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-transport-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-transport-native-epoll-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-transport-native-unix-common-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/profiles-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/protobuf-java-2.6.1.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/protocol-core-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/reactive-streams-1.0.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/regions-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/rxjava-2.1.14.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/sdk-core-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/slf4j-api-1.7.25.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/sts-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/utils-2.4.0.jar:/Users/am/Development/kclnodejs:/Users/am/Development/kclnodejs/samples/basic_sample/consumer software.amazon.kinesis.multilang.MultiLangDaemon --properties-file samples/basic_sample/consumer/sample.properties 
> ==========================================================
> Starting MultiLangDaemon ...
> Unrecognized option: -cp /Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/amazon-kinesis-client-2.1.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/amazon-kinesis-client-multilang-2.1.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/animal-sniffer-annotations-1.14.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/annotations-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/apache-client-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/auth-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-cbor-protocol-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-core-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-java-sdk-core-1.11.477.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-json-protocol-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/aws-query-protocol-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/checker-qual-2.5.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/cloudwatch-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-beanutils-1.9.3.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-codec-1.10.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-collections-3.2.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-collections4-4.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-io-2.6.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-lang3-3.8.1.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/commons-logging-1.1.3.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/dynamodb-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/error_prone_annotations-2.1.3.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/flow-1.7.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/guava-26.0-jre.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/http-client-spi-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/httpclient-4.5.6.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/httpcore-4.4.10.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/ion-java-1.0.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/j2objc-annotations-1.1.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jackson-annotations-2.9.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jackson-core-2.9.8.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jackson-databind-2.9.8.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jackson-dataformat-cbor-2.9.8.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jcommander-1.72.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/joda-time-2.8.1.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/jsr305-3.0.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/kinesis-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/logback-classic-1.2.3.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/logback-core-1.2.3.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-buffer-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-codec-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-codec-http-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-codec-http2-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-common-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-handler-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-nio-client-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-reactive-streams-2.0.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-reactive-streams-http-2.0.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-resolver-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-transport-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-transport-native-epoll-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/netty-transport-native-unix-common-4.1.32.Final.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/profiles-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/protobuf-java-2.6.1.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/protocol-core-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/reactive-streams-1.0.2.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/regions-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/rxjava-2.1.14.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/sdk-core-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/slf4j-api-1.7.25.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/sts-2.4.0.jar:/Users/am/Development/amazon-kinesis-client-nodejs/lib/jars/utils-2.4.0.jar:/Users/am/Development/kclnodejs:/Users/am/Development/kclnodejs/samples/basic_sample/consumer
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.

If I copy and paste the printed CMD property into my terminal window the process runs as expected. It seems that the issue is related to the `spawn(java, args, { stdio: 'inherit' });` command at line 165 of the kcl_bootstrap script.

**Comment by adampasz** [comment] 2019-05-31 20:08
I had same issue. PR solved it. 
2 months. No merge. :(

**Comment by mariendev** [comment] 2019-10-22 10:27
@pfifer any update on when we can expect this to be merged?

**Closed** 2024-03-07 18:08 UTC
